---
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
- jekyll-admin
- jekyll-gist
- jekyll-redirect-from
highlighter: rouge
twitter:
  username: randyzwitch
permalink: /:title/
name: randyzwitch
description: Data Science, Programming, Technology, Design
url: http://randyzwitch.com
paginate: 3
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy Zwitch"
      layout: "responsive"
      author: "Randy Zwitch"
